# Generated by Django 6.0.6 on 2026-07-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approver',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
