# Generated by Django 6.0.6 on 2026-07-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_timesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Not Verified', 'Not Verified')], default='Pending', max_length=20),
        ),
    ]
